version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

    target-branch: "main"

    labels:
      - "dependencies"
      - "php"
      - "security"

    reviewers:
      - "CodeWithSushil"

    pull-request-branch-name:
      separator: "_"

    commit-message:
      prefix: "dependabot"
      include: "scope"

    open-pull-requests-limit: 10


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    target-branch: "main"

    labels:
      - "dependencies"
      - "github-actions"
      - "security"

    reviewers:
      - "CodeWithSushil"

    pull-request-branch-name:
      separator: "_"

    commit-message:
      prefix: "dependabot"
      include: "scope"

    open-pull-requests-limit: 10
